# Workaround for https://status.dev.azure.com/_event/179641421
trigger:
  branches:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'


jobs:
  - job: cfi_tests_jdk8
    pool:
      vmImage: 'ubuntu-latest'
    container: xingweitian/ubuntu-for-cfi-jdk8:latest
    steps:
      - checkout: self
        fetchDepth: 25
      - bash: ./.travis-build.sh cfi-tests
        displayName: ./.travis-build.sh cfi-tests
  - job: cfi_tests_jdk11
    pool:
      vmImage: 'ubuntu-latest'
    container: xingweitian/ubuntu-for-cfi-jdk11:latest
    steps:
      - checkout: self
        fetchDepth: 25
      - bash: ./.travis-build.sh cfi-tests
        displayName: ./.travis-build.sh cfi-tests
  - job: downstream_ontology_jdk8
    pool:
      vmImage: 'ubuntu-latest'
    container: xingweitian/ubuntu-for-cfi-jdk8:latest
    steps:
      - checkout: self
        fetchDepth: 25
      - bash: ./.travis-build.sh downstream-ontology
        displayName: ./.travis-build.sh downstream-ontology
  - job: downstream_ontology_jdk11
    pool:
      vmImage: 'ubuntu-latest'
    container: xingweitian/ubuntu-for-cfi-jdk11:latest
    steps:
      - checkout: self
        fetchDepth: 25
      - bash: ./.travis-build.sh downstream-ontology
        displayName: ./.travis-build.sh downstream-ontology
  - job: downstream_units_jdk8
    pool:
      vmImage: 'ubuntu-latest'
    container: xingweitian/ubuntu-for-cfi-jdk8:latest
    steps:
      - checkout: self
        fetchDepth: 25
      - bash: ./.travis-build.sh downstream-units
        displayName: ./.travis-build.sh downstream-units
  - job: downstream_units_jdk11
    pool:
      vmImage: 'ubuntu-latest'
    container: xingweitian/ubuntu-for-cfi-jdk11:latest
    steps:
      - checkout: self
        fetchDepth: 25
      - bash: ./.travis-build.sh downstream-units
        displayName: ./.travis-build.sh downstream-units
  - job: downstream_security_demo_jdk8
    pool:
      vmImage: 'ubuntu-latest'
    container: xingweitian/ubuntu-for-cfi-jdk8:latest
    steps:
      - checkout: self
        fetchDepth: 25
      - bash: ./.travis-build.sh downstream-security-demo
        displayName: ./.travis-build.sh downstream-security-demo
  - job: downstream_security_demo_jdk11
    pool:
      vmImage: 'ubuntu-latest'
    container: xingweitian/ubuntu-for-cfi-jdk11:latest
    steps:
      - checkout: self
        fetchDepth: 25
      - bash: ./.travis-build.sh downstream-security-demo
        displayName: ./.travis-build.sh downstream-security-demo
