# Workaround for https://status.dev.azure.com/_event/179641421
trigger:
  branches:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'


jobs:
  - job: cfi-tests-jdk8
    pool:
      vmImage: 'ubuntu-latest'
    container: xingweitian/ubuntu-for-cfi-jdk8:latest
    steps:
      - checkout: self
        fetchDepth: 25
      - bash: ./.travis-build.sh cfi-tests
        displayName: ./.travis-build.sh cfi-tests
  - job: cfi-tests-jdk11
    pool:
      vmImage: 'ubuntu-latest'
    container: xingweitian/ubuntu-for-cfi-jdk11:latest
    steps:
      - checkout: self
        fetchDepth: 25
      - bash: ./.travis-build.sh cfi-tests
        displayName: ./.travis-build.sh cfi-tests
  - job: downstream-ontology-jdk8
    pool:
      vmImage: 'ubuntu-latest'
    container: xingweitian/ubuntu-for-cfi-jdk8:latest
    steps:
      - checkout: self
        fetchDepth: 25
      - bash: ./.travis-build.sh downstream-ontology
        displayName: ./.travis-build.sh downstream-ontology
  - job: downstream-ontology-jdk11
    pool:
      vmImage: 'ubuntu-latest'
    container: xingweitian/ubuntu-for-cfi-jdk11:latest
    steps:
      - checkout: self
        fetchDepth: 25
      - bash: ./.travis-build.sh downstream-ontology
        displayName: ./.travis-build.sh downstream-ontology
  - job: downstream-units-jdk8
    pool:
      vmImage: 'ubuntu-latest'
    container: xingweitian/ubuntu-for-cfi-jdk8:latest
    steps:
      - checkout: self
        fetchDepth: 25
      - bash: ./.travis-build.sh downstream-units
        displayName: ./.travis-build.sh downstream-units
  - job: downstream-units-jdk11
    pool:
      vmImage: 'ubuntu-latest'
    container: xingweitian/ubuntu-for-cfi-jdk11:latest
    steps:
      - checkout: self
        fetchDepth: 25
      - bash: ./.travis-build.sh downstream-units
        displayName: ./.travis-build.sh downstream-units
  - job: downstream-security-demo-jdk8
    pool:
      vmImage: 'ubuntu-latest'
    container: xingweitian/ubuntu-for-cfi-jdk8:latest
    steps:
      - checkout: self
        fetchDepth: 25
      - bash: ./.travis-build.sh downstream-security-demo
        displayName: ./.travis-build.sh downstream-security-demo
  - job: downstream-security-demo-jdk11
    pool:
      vmImage: 'ubuntu-latest'
    container: xingweitian/ubuntu-for-cfi-jdk11:latest
    steps:
      - checkout: self
        fetchDepth: 25
      - bash: ./.travis-build.sh downstream-security-demo
        displayName: ./.travis-build.sh downstream-security-demo
