package checkers.inference.solver.backend.logiql;

import org.checkerframework.javacutil.BugInCF;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.List;

/**
 * LogicBloxRunner send two .logic file generated by LogiqlConstraintGenerator and
 * LogiqlDataGenerator to Logicblox, and write the output from database to file logicbloxOutput.txt.
 *
 * @author Jianchu Li
 */
public class LogicBloxRunner {

    private String inReply = "";
    private final String path;
    private final int nth;

    public LogicBloxRunner(String path, int nth) {
        this.path = path;
        this.nth = nth;
    }

    /** runLogicBlox run each command of logicblox. */
    public void runLogicBlox() {
        List<List<String>> commands =
                Arrays.asList(
                        Arrays.asList("lb", "create", "pltest"),
                        Arrays.asList(
                                "lb",
                                "addblock",
                                "pltest",
                                "-f" + path + "/logiqlEncoding" + nth + ".logic"),
                        Arrays.asList(
                                "lb", "exec", "pltest", "-f" + path + "/data" + nth + ".logic"),
                        Arrays.asList("lb", "print", "pltest", "orderedAnnotationOf"),
                        Arrays.asList("lb", "delete", "pltest"));
        for (int i = 0; i < commands.size(); i++) {
            try {
                getOutPut_Error(commands.get(i), i);
            } catch (IOException | InterruptedException e) {
                throw new BugInCF("Failed to run LogicBlox command: " + commands.get(i), e);
            }
        }
        writeFile(inReply);
    }

    /**
     * run command and get the output and error from logicblox.
     *
     * @param command is the command and arguments.
     * @param i
     * @throws IOException
     * @throws InterruptedException
     */
    private void getOutPut_Error(List<String> command, final int i)
            throws IOException, InterruptedException {
        final Process p = new ProcessBuilder(command).start();
        Thread getOutPut =
                new Thread() {
                    @Override
                    public void run() {
                        String s = "";
                        BufferedReader stdInput =
                                new BufferedReader(
                                        new InputStreamReader(
                                                p.getInputStream(), StandardCharsets.UTF_8));
                        try {
                            while ((s = stdInput.readLine()) != null) {
                                if (i == 3) {
                                    inReply = inReply + s + "\n";
                                    // System.out.println(s);
                                }
                            }
                        } catch (NumberFormatException | IOException e) {
                            throw new BugInCF("Error reading LogicBlox output.", e);
                        }
                    }
                };
        getOutPut.start();

        Thread getError =
                new Thread() {
                    @Override
                    public void run() {
                        String s = "";
                        BufferedReader stdError =
                                new BufferedReader(
                                        new InputStreamReader(
                                                p.getErrorStream(), StandardCharsets.UTF_8));
                        try {
                            while ((s = stdError.readLine()) != null) {
                                // Drain stderr so the process cannot block on a full error stream.
                            }
                        } catch (IOException e) {
                            throw new BugInCF("Error reading LogicBlox errors.", e);
                        }
                    }
                };
        getError.start();
        getOutPut.join();
        getError.join();
        p.waitFor();
    }

    /** write the result from LogicBlox to logicbloxOutput.txt. */
    private void writeFile(String output) {
        try (PrintWriter pw =
                new PrintWriter(
                        Files.newBufferedWriter(
                                Paths.get(path, "logicbloxOutput" + nth + ".txt"),
                                StandardCharsets.UTF_8))) {
            pw.write(output);
        } catch (Exception e) {
            throw new BugInCF("Failed to write LogicBlox output.", e);
        }
    }
}
