#!/bin/sh

#
# This file simply redirects all passed arguments
# to checkers.inference.InferenceLauncher
#

myDir="`dirname $0`"
case `uname -s` in
    CYGWIN*)
      myDir=`cygpath -m $mydir`
      ;;
esac

if [ "$myDir" = "" ];
then
    myDir="."
fi

JSR308=$(cd ${myDir}/../../ && pwd)

distDir=$myDir"/../dist"

libDir=$JSR308/"checker-framework-inference/lib"

classpath="$distDir"/checker.jar:"$distDir"/annotation-file-utilities.jar:"$distDir"/checker-framework-inference.jar

if [ "$external_checker_classpath" != "" ] ; then
    classpath=${classpath}:${external_checker_classpath}
fi

export DYLD_LIBRARY_PATH=${libDir}
export LD_LIBRARY_PATH=${libDir}

eval "java -classpath  "$classpath" checkers.inference.InferenceLauncher " "$@"
