name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        group: [ cfi-tests, downstream-ontology, downstream-security-demo ]
        jdk: [ jdk8, jdk11 ]
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install ant cpp gradle jq libcurl3-gnutls make maven mercurial python3-requests unzip wget binutils build-essential
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Pull Request
        if: github.head_ref != ''
        run: |
          if [ ${{ github.repository_owner }} != opprop ] ; then
            git config user.email noone@cares.com
            git config user.name Noone Cares
            git fetch theupstream ${{ github.event.pull_request.base.repo.clone_url }}
            git checkout -b ${{ github.head_ref }} theupstream/${{ github.head_ref }}
          fi
      - name: Build
        run: |
          export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
          ./.ci-build.sh ${{ matrix.group }}
