name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        group: [ cfi-tests, downstream-ontology, downstream-security-demo ]
        jdk: [ jdk8, jdk11 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "REMOTE_ORIGIN_URL=`git config --get remote.origin.url`" >> $GITHUB_ENV
      - uses: addnab/docker-run-action@v1
        with:
          image: xingweitian/ubuntu-for-cfi-${{ matrix.jdk }}
          run: |
            /bin/bash -c "true &&
            branch='' &&
            if [ "${{ github.head_ref }}" == "" ] ; then
              echo "Branch=`echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||'`"
              branch=`echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||'`
            else
              echo "Branch=`echo ${{ github.head_ref }} | sed -E 's|refs/[a-zA-Z]+/||'`"
              branch=`echo ${{ github.head_ref }} | sed -E 's|refs/[a-zA-Z]+/||'`
            fi &&
            git clone -b $branch ${{ env.REMOTE_ORIGIN_URL }} &&
            echo "REMOTE_ORIGIN_URL=${{ env.REMOTE_ORIGIN_URL }}" &&
            git clone -b ${{ github.head_ref }} ${{ env.REMOTE_ORIGIN_URL }} &&
            cd checker-framework-inference &&
            export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8 &&
            ./.travis-build.sh ${{ matrix.group }}"
